Metrics/LineLength:
  Max: 100
  Exclude:
    - edi_safe.gemspec

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/HashSyntax:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
