name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-18.04
    steps:
      - name: Get Packages for Ruby Prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git curl libssl1.0-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
      - name: Install Ruby
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
          tar xjf ruby-2.1.10.tar.bz2
          cd ruby-2.1.10 && ./configure && make -j 2
          sudo make install
      - uses: actions/checkout@v2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-edi_safe--gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-edi_safe-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.17.3'
          bundle config path vendor/bundle
          bundle install
      - name: run rubocop
        run: |
          bundle exec rubocop
      - name: run tests
        run: |
          bundle exec rspec
